#! /bin/sh
## BSPWM Configurations
sxhkd &
bspc monitor eDP-1 -d             &
bspc config border_width        1	        &
bspc config window_gap          10	        &
bspc config right_padding       55	        &
bspc config split_ratio         0.52	    &
bspc config borderless_monocle  true	    &
bspc config gapless_monocle     true	    &
nitrogen --restore                          &

## Tray programs
killall tint2       ;
killall cbatticon   ;
killall volumeicon  ;
tint2               &
nm-applet           &
volumeicon          &
blueman-manager     &
batsignal           &
flameshot           &
cbatticon           &
qpwgraph            &

## Autostart programs
bspc rule -a kitty          --one-shot  desktop='^1' ; kitty &
bspc rule -a code           --one-shot  desktop='^2' ; code &
bspc rule -a firefox        --one-shot  desktop='^3' ; firefox &
bspc rule -a anki           --one-shot  desktop='^4' ; anki &
bspc rule -a qbittorrent    --one-shot  desktop='^6' ; qbittorrent &
bspc rule -a kitty          --one-shot  desktop='^6' ; kitty &
bspc rule -a steam          --one-shot  desktop='^7' ; steam & sleep 20 ; #sleep to get both windows
bspc rule -a notion-app-enhanced --one-shot desktop='^8' ; notion-app-enhanced &
bspc rule -a prospect-mail  --one-shot  desktop='^9' ; prospect-mail &
bspc rule -a discord        --one-shot  desktop='^9'; discord &

## Fix taskbar fullscreen
xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2) ;
notify-send "Workspace setup completed "