#! /bin/sh

SECOND_MONITOR_SIDE="rigth"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')

sxhkd &

# Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I
  bspc monitor $(bspc query -M | sed -n 2p) -d II III IV V VI VII VIII IX X
  #Set Monitors Side and output 
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL  
else
  bspc monitor -d I II III IV V VI VII VIII IX X 
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a alacritty desktop='^1' follow=off -o
bspc rule -a prospect-mail desktop='^9' follow=off -o
bspc rule -a notion-app-enhanced desktop='^10' follow=off -o
bspc rule -a qbittorrent desktop='^8' follow=off -o
bspc rule -a steam desktop='^7' follow=off -o
bspc rule -a firefox desktop='^1' follow=off -o
bspc rule -a discord desktop='^8' follow=off -o
#bspc rule -a alacritty desktop='^1'


## run programs
nm-applet &
cbatticon &
volumeicon &
batsignal &
flameshot &
qpwgraph #&
#qbittorrent &
#discord &
#alacritty &
#notion-app-enhanced &
#firefox &
#prospect-mail


